service: SLSWORDLGENERATEWORD
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  generate:
    handler: handler.generate
    events:
      - httpApi:
          path: /
          method: get
